name: Frontend Dev CI

on:
  push:
    branches:
      - develop

permissions:
  contents: write

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t trishank01/taskmanager-frontend:${IMAGE_TAG} .

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: trishank01/taskmanager-frontend:${{ env.IMAGE_TAG }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Push Docker Image
        run: |
          docker push trishank01/taskmanager-frontend:${IMAGE_TAG}
      
      - name: Update K8s Manifest Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/trishank01/task-manager-k8s.git

          cd task-manager-k8s

          sed -i "s|image: trishank01/taskmanager-frontend:.*|image: trishank01/taskmanager-frontend:${IMAGE_TAG}|g" dev/frontend/deployment.yaml

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          git commit -m "update frontend dev image to ${IMAGE_TAG}"

          git push